// Made by loxqcx on Discord.
export const packagesPageConfig = {
  hero: {
    eyebrow: 'Packages',
    title: ['Pick the pace.', "We'll build the system."],
    body: 'Six focused packages across content, PTR acquisition, and game growth optimization.',
    aside: 'Choose a set package or join our Discord to build a custom scope.',
  },
  packages: [
    {
      name: 'Starter',
      category: 'Content',
      price: '$544',
      cadence: 'per month',
      description: 'For developers looking to build a consistent content presence. Best for games looking to establish consistent short-form content.',
      featured: false,
      includes: [
        '12 short-form videos per month',
        'Content strategy',
        'Video concepts based on current trends',
        'Editing and post-production',
        'Captions and hooks',
        'Content scheduling',
        'Monthly performance report',
        'Views and engagement tracking',
        'Top-performing content analysis',
        'Recommendations for the following month',
      ],
    },
    {
      name: 'Growth',
      category: 'Content',
      price: '$817',
      cadence: 'per month',
      description: 'For developers looking to scale their content and actively optimize based on performance. Best for games that already have content running and want to consistently improve its performance.',
      featured: true,
      includes: [
        '16 short-form videos per month',
        'Everything included in Starter',
        'A/B testing of hooks and concepts',
        'Trend research',
        'Content iteration based on previous performance',
        'Greater focus on game-specific content',
        'Biweekly performance reports',
        'Video-by-video performance analysis',
        'Engagement and retention analysis',
        'Identification of winning content formats',
        'Monthly content strategy adjustment',
        'Competitor and content trend analysis',
      ],
    },
    {
      name: 'Scale',
      category: 'Content',
      price: '$1,363',
      cadence: 'per month',
      description: 'For studios that want RoViral to operate their short-form content strategy at scale. Best for studios that want a serious, data-driven short-form content operation.',
      featured: false,
      includes: [
        '25 short-form videos per month',
        'Everything included in Growth',
        'Advanced content strategy',
        'Multiple content formats',
        'High-volume trend testing',
        'Rapid iteration of successful concepts',
        'Priority content production',
        'Platform-specific optimization',
        'Weekly performance reporting',
        'Detailed content analytics',
        'Individual video performance breakdowns',
        'Trend and competitor analysis',
        'Monthly content performance review',
        'Monthly strategy planning',
        'Continuous optimization based on performance data',
      ],
    },
    {
      name: 'PTR Starter',
      category: 'PTR',
      price: '$544',
      cadence: 'per month',
      description: 'For developers looking to establish PTR as a consistent source of player acquisition.',
      featured: false,
      includes: [
        '10 thumbs per week',
        'Up to 40 thumbs per month',
        'PTR campaign planning',
        'Targeted player outreach',
        'Campaign scheduling',
        'PTR coordination',
        'Campaign monitoring',
        'Performance tracking',
        'Monthly campaign report',
        'Total players driven',
        'Peak and average CCU reporting',
        'Session and campaign performance',
        'Recommendations for future PTR campaigns',
      ],
    },
    {
      name: 'PTR Growth',
      category: 'PTR',
      price: '$1,227',
      cadence: 'per month',
      description: 'For studios that want PTR to become a major, high-volume part of their player acquisition strategy.',
      featured: false,
      includes: [
        '25 thumbs per week',
        'Up to 100 thumbs per month',
        'Full PTR campaign strategy',
        'Target audience identification',
        'Targeted player outreach',
        'Campaign scheduling and coordination',
        'Campaign monitoring',
        'Performance optimization',
        'Priority PTR support',
        'Detailed monthly performance report',
        'Total players driven',
        'Peak and average CCU reporting',
        'Session length and player engagement',
        'Retention signals where available',
        'Campaign-by-campaign performance',
        'Performance trends',
        'Recommendations for future campaigns',
      ],
    },
    {
      name: 'Game Growth Audit',
      category: 'Game Growth',
      price: '$408',
      cadence: 'one-time',
      description: 'A comprehensive Roblox game review that identifies what is limiting growth and provides a clear plan for improvement.',
      featured: false,
      includes: [
        'KPI analysis: CCU, session time, D1 and D7 retention',
        'Player acquisition, conversion, playtime, and frequency analysis',
        'Player drop-off and monetization performance analysis',
        'First-time experience, gameplay loop, and progression review',
        'Onboarding, pacing, endgame, and update structure review',
        'Gamepasses, developer products, UI/UX, and social mechanics review',
        'Replayability analysis',
        'Detailed Game Growth Report',
        'Impact-ranked problems and priorities',
        'Specific recommendations and growth opportunities',
        'Prioritized action plan for the development team',
      ],
    },
  ],
  featuredLabel: 'Most popular',
  inquiryLabel: 'Learn more',
  note: {
    title: 'Need a custom package?',
    body: 'Join the RoViral Discord server and tell us what your game needs. We will build a package around your goals.',
    linkLabel: 'Join the server',
    linkUrl: 'https://discord.gg/UCMjNhMRtk',
    icon: '/assets/DiscordLogo.png',
  },
};
