// Made by loxqcx on Discord.
export const reviewsConfig = {
  sectionId: 'reviews',
  eyebrow: 'Client reviews',
  title: ['Built with teams.', 'Backed by results.'],
  body: 'Feedback from the developers and teams we have worked alongside.',
  emptyMessage: 'Approved client reviews will appear here.',
  marqueeDurationSeconds: 46,
  refreshMs: 10_000,
  form: {
    openLabel: 'Leave a review',
    closeLabel: 'Close form',
    title: 'Share your experience',
    discordLabel: 'Discord username or user ID',
    discordPlaceholder: 'username or 123456789012345678',
    nameLabel: 'Name (optional)',
    namePlaceholder: 'Name shown on the review',
    messageLabel: 'Your experience',
    messagePlaceholder: 'Tell us what it was like working with RoViral.',
    starsLabel: 'Stars',
    submitLabel: 'Send review',
    loadingLabel: 'Sending...',
    successTitle: 'Review sent',
    successBody: 'Your review is waiting for approval.',
    resetLabel: 'Send another review',
  },
  moderation: {
    channelId: '1541656718214307860',
    moderatorUserIds: [],
    approvalEmoji: '\u2705',
    denialEmoji: '\u274c',
    footerPrefix: 'RoViral Review',
    idPrefix: 'review',
    colors: {
      pending: 0xf0c94c,
      approved: 0x20ef55,
      denied: 0xe05252,
      declined: 0xe05252,
      deleted: 0xe05252,
    },
    approvedMessage: 'Review approved',
    declinedMessage: 'Review declined',
    deleteCommand: {
      name: 'deleter',
      description: 'Delete a review by its review ID.',
      optionName: 'id',
      optionDescription: 'The review ID shown in the Discord embed footer.',
      scanLimit: 500,
      successMessage: 'Review marked as deleted. It will disappear after the next website refresh.',
      notFoundMessage: 'No review was found with that ID.',
      deniedMessage: 'You do not have permission to delete reviews.',
    },
    deleteAllCommand: {
      name: 'deleteallrev',
      description: 'Mark every review deleted and remove them from the website.',
      successMessage: 'All reviews have been deleted',
      deletedTitle: 'Deleted',
    },
  },
};
