// Made by loxqcx on Discord.
import { announcementConfig, brandConfig, footerConfig } from './brand';
import { homepageMetrics } from './metrics';
import { navigationConfig } from './navigation';

export const siteConfig = {
  brand: brandConfig,
  announcement: announcementConfig,
  navigation: navigationConfig,
  hero: {
    eyebrow: 'The attention layer for Roblox games',
    titleLines: ['Built to be', 'played. Made', 'to go viral.'],
    body: 'Strategy, short-form content, community, and trailers under one roof. We turn good Roblox games into launches people notice.',
    primaryCta: { label: 'Start a project', path: '/contact' },
    secondaryCta: { label: 'See our work', path: '/portfolio' },
    stats: homepageMetrics,
  },
  services: [
    {
      id: '01',
      title: 'Short Form Content Creation',
      shortTitle: 'Short form',
      description: 'Platform-native videos built around hooks, repeatable formats, and the moments players want to share.',
      deliverables: ['Creative concepts', 'Editing and captions', 'Platform-ready exports', 'Performance iteration'],
      accent: 'lime',
    },
    {
      id: '02',
      title: 'Content Creation Management',
      shortTitle: 'Content ops',
      description: 'A complete content pipeline, from creator briefs and calendars to approvals, publishing, and reporting.',
      deliverables: ['Monthly content plan', 'Creator coordination', 'Publishing calendar', 'Weekly reporting'],
      accent: 'coral',
    },
    {
      id: '03',
      title: 'Community Management',
      shortTitle: 'Community',
      description: 'Human, fast, on-brand community care that turns players into regulars and regulars into advocates.',
      deliverables: ['Discord operations', 'Event programming', 'Feedback reports', 'Moderation playbooks'],
      accent: 'cyan',
    },
    {
      id: '04',
      title: 'PTR Boosting',
      shortTitle: 'PTR growth',
      description: 'Thumbnail and icon testing that improves the first impression your game makes on discovery surfaces.',
      deliverables: ['Visual audit', 'Creative variants', 'Test roadmap', 'Performance review'],
      accent: 'yellow',
    },
    {
      id: '05',
      title: 'Roblox Game Growth Audit',
      shortTitle: 'Growth audit',
      description: 'A clear diagnostic of your acquisition funnel, positioning, content, community, and growth blockers.',
      deliverables: ['90-minute workshop', 'Channel analysis', 'Prioritized roadmap', '30-day action plan'],
      accent: 'lime',
    },
    {
      id: '06',
      title: 'Game Trailers',
      shortTitle: 'Trailers',
      description: 'Launch trailers and update teasers paced for attention, clarity, and the exact promise of your game.',
      deliverables: ['Creative direction', 'Capture plan', 'Edit and sound design', 'Multi-format delivery'],
      accent: 'coral',
    },
  ],
  packages: [
    {
      name: 'Launch',
      kicker: 'For a focused release',
      price: 'Custom',
      cadence: 'one-time sprint',
      description: 'A concentrated creative push for a new game, major update, or seasonal beat.',
      featured: false,
      includes: ['Growth audit', 'Launch strategy', '12 short-form videos', '1 launch trailer', 'Campaign report'],
    },
    {
      name: 'Momentum',
      kicker: 'The growth operating system',
      price: 'Custom',
      cadence: 'monthly',
      description: 'An always-on content and community engine for teams ready to build compounding attention.',
      featured: true,
      includes: ['Content strategy and calendar', '20 short-form videos', 'Creator management', 'Community management', 'PTR creative testing', 'Weekly performance sync'],
    },
    {
      name: 'Studio+',
      kicker: 'For ambitious live games',
      price: 'Custom',
      cadence: 'monthly',
      description: 'A flexible embedded growth team across content, creative testing, launches, and community.',
      featured: false,
      includes: ['Everything in Momentum', 'High-volume content', 'Dedicated growth lead', 'Monthly trailers and teasers', 'Priority turnaround', 'Custom reporting'],
    },
  ],
  portfolio: [
    {
      slug: 'velocity-racers',
      title: 'Velocity Racers',
      category: 'Launch Campaign',
      result: '2.8M organic views',
      description: 'A fast, creator-led launch system that made every race feel like a shareable moment.',
      palette: ['#0f3d1e', '#21ef55', '#050806'],
      motif: 'speed',
      year: '2026',
    },
    {
      slug: 'harvest-together',
      title: 'Harvest Together',
      category: 'Community + Content',
      result: '+186% Discord activity',
      description: 'A cozy content universe built around player stories, seasonal rituals, and weekly community beats.',
      palette: ['#c7ff70', '#168b3a', '#050806'],
      motif: 'garden',
      year: '2026',
    },
    {
      slug: 'night-shift',
      title: 'Night Shift',
      category: 'PTR Optimization',
      result: '+41% play rate',
      description: 'A sharper visual promise, disciplined creative testing, and a discovery page players understood instantly.',
      palette: ['#43d982', '#050806', '#dfffe6'],
      motif: 'signal',
      year: '2025',
    },
  ],
  process: [
    { step: '01', title: 'Find the signal', text: 'We audit the game, audience, and current content to identify the strongest reason to care.' },
    { step: '02', title: 'Build the system', text: 'We turn that signal into repeatable formats, a channel plan, and a production rhythm.' },
    { step: '03', title: 'Ship and learn', text: 'Creative goes live quickly, then performance shapes the next round instead of sitting in a deck.' },
  ],
  team: [
    { name: 'Alex Rivera', role: 'Founder / Growth Strategy', initials: 'AR', accent: 'lime', bio: 'Turns game truths into sharp market positions and practical growth systems.' },
    { name: 'Maya Chen', role: 'Creative Director', initials: 'MC', accent: 'coral', bio: 'Leads visual concepts, trailers, and content formats that land in the first second.' },
    { name: 'Jordan Brooks', role: 'Community Lead', initials: 'JB', accent: 'cyan', bio: 'Builds communities with actual rhythm, useful feedback loops, and a human voice.' },
    { name: 'Sam Okafor', role: 'Content Operations', initials: 'SO', accent: 'yellow', bio: 'Keeps creators, calendars, approvals, and performance reporting moving together.' },
  ],
  careers: [
    { title: 'Video Editor', type: 'Contract / Remote', description: 'Turn raw Roblox gameplay and creator footage into sharp, platform-native short-form stories.', skills: ['Premiere or Resolve', 'Short-form pacing', 'Motion graphics', 'Roblox fluency'] },
    { title: 'Content Creator Manager', type: 'Contract / Remote', description: 'Own creator communication, briefs, calendars, feedback, and campaign delivery.', skills: ['Creator operations', 'Clear communication', 'Campaign tracking', 'Platform knowledge'] },
    { title: 'Clipper', type: 'Flexible / Remote', description: 'Find the moments worth watching and package them into high-volume, high-energy clips.', skills: ['Great taste', 'Fast editing', 'Hook writing', 'Trend awareness'] },
  ],
  contact: {
    heading: 'Let’s make your game the next thing people talk about.',
    subheading: 'Tell us what you are building, where it is right now, and what growth would look like. We usually reply within one business day.',
    budgetOptions: ['Under $2,500', '$2,500 - $5,000', '$5,000 - $10,000', '$10,000+', 'Not sure yet'],
    serviceOptions: ['Short Form Content Creation', 'Content Creation Management', 'Community Management', 'PTR Boosting', 'Roblox Game Growth Audit', 'Game Trailers'],
  },
  footer: footerConfig,
};
